bootstrap_menu:
  menus:
    main:
    anonymousaccount:
      items:
        account:
          label: 'Account'
          items:
            login:
              label: 'Login'
              route: 'app_login'
#            register:
#              label: 'Register'
#              route: 'app_register'
    account:
      items:
        account:
          label: 'Account'
          items:
            logout:
              label: 'Logout'
              route: 'app_logout'
              roles: [ 'ROLE_USER' ]